In [7]:
import os
import pandas as pd 
import numpy as np
import cv2
import matplotlib.pyplot as plt


In [8]:
data=[]
colors=[]

In [9]:
path="C:/Users/charan/Downloads/archive/training_dataset"
  

In [10]:
for dir in os.listdir(path):
    for img in os.listdir(path+'/'+dir):
        image=cv2.imread(path+'/'+dir+'/'+img)
        data.append(image[0][0])
        colors.append(dir)
        print(image[0][0],"  ",dir)

[ 2  5 10]    black
[17  0 17]    black
[23 24 29]    black
[47 47 47]    black
[33 29 28]    black
[68 71 76]    black
[7 2 1]    black
[8 0 4]    black
[7 7 4]    black
[5 5 5]    black
[8 8 8]    black
[ 2  5 10]    black
[23 23 23]    black
[7 2 1]    black
[0 0 0]    black
[8 0 4]    black
[0 0 0]    black
[2 2 2]    black
[2 2 2]    black
[39 36 31]    black
[57 54 49]    black
[0 0 0]    black
[37 37 37]    black
[54 49 48]    black
[54 48 53]    black
[255   0   0]    blue
[119  51   0]    blue
[186  72   0]    blue
[179 117   0]    blue
[179 119   0]    blue
[255 127   0]    blue
[106  56   1]    blue
[252 101   1]    blue
[53  0  2]    blue
[120  42   6]    blue
[233 191  12]    blue
[87 59 15]    blue
[210 116  25]    blue
[221 193  26]    blue
[168 130  34]    blue
[237 160  36]    blue
[254 253  65]    blue
[142 115  79]    blue
[210 169 109]    blue
[219 173 132]    blue
[188  91   3]    blue
[176  12   0]    blue
[255   0   0]    blue
[143  48   0]    blue
[193 119   1] 

In [11]:
df = pd.DataFrame(data, columns=['b', 'g', 'r'])
df["color"]=colors
df

b    g    r   color
0      2    5   10   black
1     17    0   17   black
2     23   24   29   black
3     47   47   47   black
4     33   29   28   black
..   ...  ...  ...     ...
245  255  255  255  yellow
246    0  255  255  yellow
247    0  166  255  yellow
248   94  217  249  yellow
249   39  191  246  yellow

[250 rows x 4 columns]

In [12]:
df.to_csv('colors.csv', index=False)